### ISSUE TITLE
Fehler beim flashen

### ISSUE THREAD

**Issue by rascaldi** [jp112sdl/SonoffDualHVIOHMLOX#2]
Hallo,
ich habe den Sonoff CH4 versehentlich mit der Firmeware geflashed. Kann ich das irgendwie rückgängig machen? 
Ich komme auch nicht mehr über USB  in den Flashmode.
Wlan funktioniert einwandfrei.
Danke im Voraus.
Viele Grüße Gerd

**Comment by jp112sdl** [comment]
Hi.
Nein, das kann man nicht rückgängig machen. 
Du kannst nur eine andere Firmware flashen, zB Tasmota.
Den Flash-Modus aktiviert man eigentlich über eine Brücke zwischen GPIO0 und GND am ESP.

VG,
Jérôme

**Comment by rascaldi** [comment]
Danke für die schnelle Antwort. 
Probiere ich morgen gleich aus.
Einen schönen Abend. 
Viele Grüße 
Gerd 
-- 
Sollten Sie diese Mail irrtümlich erhalten haben, bitte ich Sie, sie ungelesen zu löschen 
--Am 12.08.2018, 21:10, "Jérôme" <notifications@github.com> schrieb:
Hi.
Nein, das kann man nicht rückgängig machen.
Du kannst nur eine andere Firmware flashen, zB Tasmota.
Den Flash-Modus aktiviert man eigentlich über eine Brücke zwischen GPIO0 und GND am ESP.
VG,
Jérôme

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jp112sdl/SonoffDualHVIOHMLOX","title":"jp112sdl/SonoffDualHVIOHMLOX","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jp112sdl/SonoffDualHVIOHMLOX"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jp112sdl in #2: Hi.\r\nNein, das kann man nicht rückgängig machen. \r\nDu kannst nur eine andere Firmware flashen, zB Tasmota.\r\nDen Flash-Modus aktiviert man eigentlich über eine Brücke zwischen GPIO0 und GND am ESP.\r\n\r\nVG,\r\nJérôme"}],"action":{"name":"View Issue","url":"https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412364947"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412364947",
"url": "https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412364947",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jp112sdl/SonoffDualHVIOHMLOX] Fehler beim flashen (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Jérôme**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jp112sdl",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jp112sdl/SonoffDualHVIOHMLOX\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jp112sdl/SonoffDualHVIOHMLOX\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412364947"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367431968\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by rascaldi** [comment]
Guten Abend, 
hat mit Tasmota geklappt.
Besser finde ich deine Lösung. 
Wirst du für den Sonoff CH-4 irgendwann eine Firmware erstellen? 
Einen schönen Abend 
Gerd 
-- 
Sollten Sie diese Mail irrtümlich erhalten haben, bitte ich Sie, sie ungelesen zu löschen 
--Am 12.08.2018, 21:10, "Jérôme" <notifications@github.com> schrieb:
Hi.
Nein, das kann man nicht rückgängig machen.
Du kannst nur eine andere Firmware flashen, zB Tasmota.
Den Flash-Modus aktiviert man eigentlich über eine Brücke zwischen GPIO0 und GND am ESP.
VG,
Jérôme

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jp112sdl/SonoffDualHVIOHMLOX","title":"jp112sdl/SonoffDualHVIOHMLOX","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jp112sdl/SonoffDualHVIOHMLOX"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jp112sdl in #2: Hi.\r\nNein, das kann man nicht rückgängig machen. \r\nDu kannst nur eine andere Firmware flashen, zB Tasmota.\r\nDen Flash-Modus aktiviert man eigentlich über eine Brücke zwischen GPIO0 und GND am ESP.\r\n\r\nVG,\r\nJérôme"}],"action":{"name":"View Issue","url":"https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412364947"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412364947",
"url": "https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412364947",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jp112sdl/SonoffDualHVIOHMLOX] Fehler beim flashen (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Jérôme**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jp112sdl",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jp112sdl/SonoffDualHVIOHMLOX\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jp112sdl/SonoffDualHVIOHMLOX\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412364947"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367431968\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by jp112sdl** [comment]
> Wirst du für den Sonoff CH-4 irgendwann eine Firmware erstellen?

Nein da wird nichts kommen. Den Sonoff 4CH nutze ich umgebaut auf HomeMatic Funk.
https://homematic-forum.de/forum/viewtopic.php?f=76&t=43718

**Comment by rascaldi** [comment]
Absolut geniale Lösung! @ 👍👍👍
-- 
Sollten Sie diese Mail irrtümlich erhalten haben, bitte ich Sie, sie ungelesen zu löschen 
--Am 14.08.2018, 16:09, "Jérôme" <notifications@github.com> schrieb:

Wirst du für den Sonoff CH-4 irgendwann eine Firmware erstellen?

Nein da wird nichts kommen. Den Sonoff 4CH nutze ich umgebaut auf HomeMatic Funk.
https://homematic-forum.de/forum/viewtopic.php?f=76&t=43718

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jp112sdl/SonoffDualHVIOHMLOX","title":"jp112sdl/SonoffDualHVIOHMLOX","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jp112sdl/SonoffDualHVIOHMLOX"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jp112sdl in #2: \u003e Wirst du für den Sonoff CH-4 irgendwann eine Firmware erstellen?\r\n\r\nNein da wird nichts kommen. Den Sonoff 4CH nutze ich umgebaut auf HomeMatic Funk.\r\nhttps://homematic-forum.de/forum/viewtopic.php?f=76\u0026t=43718"}],"action":{"name":"View Issue","url":"https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412884974"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412884974",
"url": "https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412884974",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jp112sdl/SonoffDualHVIOHMLOX] Fehler beim flashen (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Jérôme**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jp112sdl",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jp112sdl/SonoffDualHVIOHMLOX\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jp112sdl/SonoffDualHVIOHMLOX/issues/2#issuecomment-412884974"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367431968\n}"
}
],
"themeColor": "26292E"
}
]
